@host = http://localhost:5136

GET {{host}}/check
Authorization: Bearer eyJbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzVhOTgzZi0wOGVhLTQ5OGEtODg2Ny0wNWRiNGUwZjMzYTQiLCJuYW1lIjoiUm9ubnkiLCJqdGkiOiI0NTVmZDU5OS02NDEyLTQ3M2ItYjE0OS1mYThiZDg0YzE4MzEiLCJleHAiOjE2NjQ3MzYxMTAsImlzcyI6Ikl0ZW1HZW5lcmF0b3IiLCJhdWQiOiJJdGVtR2VuZXJhdG9yIn0.v5O7VtvYSz4PjvUTCgWonYE0jfOTAimGgHOvXY5JDas