using ItemGenerator.Domain.Common;

namespace ItemGenerator.Domain.Enumerations;

public sealed class AffixClass : Enumeration<AffixClass>
{
    private AffixClass(byte value, string name) : base(value, name) { }
    public static readonly AffixClass AddSockets = new(0, "AddSockets");
    public static readonly AffixClass AttackRating = new(1, "AttackRating");
    public static readonly AffixClass AttackRatingAndDamageBasedOnCharacterLevel = new(2, "AttackRatingAndDamageBasedOnCharacterLevel");
    public static readonly AffixClass AttackRatingBasedOnCharacterLevel = new(3, "AttackRatingBasedOnCharacterLevel");
    public static readonly AffixClass AttackRatingPercentBasedOnCharacterLevel = new(4, "AttackRatingPercentBasedOnCharacterLevel");
    public static readonly AffixClass AttackRatingAndEnhancedDamageVsDemons = new(5, "AttackRatingAndEnhancedDamageVsDemons");
    public static readonly AffixClass AttackRatingAndEnhancedDamageVsUndead = new(6, "AttackRatingAndEnhancedDamageVsUndead");
    public static readonly AffixClass AttackSpeed = new(7, "AttackSpeed");
    public static readonly AffixClass BlockRateAndChance = new(8, "BlockRateAndChance");
    public static readonly AffixClass CauseMonsterFlee = new(9, "CauseMonsterFlee");
    public static readonly AffixClass CastRate = new(10, "CastRate");
    public static readonly AffixClass DamageCold = new(11, "DamageCold");
    public static readonly AffixClass DamageEnhanced = new(12, "DamageEnhanced");
    public static readonly AffixClass DamageFire = new(13, "DamageFire");
    public static readonly AffixClass DamageLightning = new(14, "DamageLightning");
    public static readonly AffixClass DamageMagicReduced = new(15, "DamageMagicReduced");
    public static readonly AffixClass DamagePhysical = new(16, "DamagePhysical");
    public static readonly AffixClass DamagePoison = new(17, "DamagePoison");
    public static readonly AffixClass DamageReduced = new(18, "DamageReduced");
    public static readonly AffixClass DamageReflect = new(19, "DamageReflect");
    public static readonly AffixClass DamageTakenGoesToMana = new(20, "DamageTakenGoesToMana");
    public static readonly AffixClass Defense = new(21, "Defense");
    public static readonly AffixClass DefenseBasedOnCharacterLevel = new(22, "DefenseBasedOnCharacterLevel");
    public static readonly AffixClass DefenseEnhanced = new(23, "DefenseEnhanced");
    public static readonly AffixClass Dexterity = new(24, "Dexterity");
    public static readonly AffixClass Energy = new(25, "Energy");
    public static readonly AffixClass FreezeDuration = new(26, "FreezeDuration");
    public static readonly AffixClass GoldFind = new(27, "GoldFind");
    public static readonly AffixClass HitRecovery = new(28, "HitRecovery");
    public static readonly AffixClass IgnoreTargetDefense = new(29, "IgnoreTargetDefense");
    public static readonly AffixClass IncreasedStackSize = new(30, "IncreasedStackSize");
    public static readonly AffixClass Indestructable = new(31, "Indestructable");
    public static readonly AffixClass Knockback = new(32, "Knockback");
    public static readonly AffixClass Life = new(33, "Life");
    public static readonly AffixClass LifeBasedOnCharacterLevel = new(34, "LifeBasedOnCharacterLevel");
    public static readonly AffixClass LifeLeech = new(35, "LifeLeech");
    public static readonly AffixClass LightRadius = new(36, "LightRadius");
    public static readonly AffixClass LightRadiusAndAttackRating = new(37, "LightRadiusAndAttackRating");
    public static readonly AffixClass LifeRegeneration = new(38, "LifeRegeneration");
    public static readonly AffixClass MagicFind = new(39, "MagicFind");
    public static readonly AffixClass Mana = new(40, "Mana");
    public static readonly AffixClass ManaBasedOnCharacterLevel = new(41, "ManaBasedOnCharacterLevel");
    public static readonly AffixClass ManaLeech = new(42, "ManaLeech");
    public static readonly AffixClass ManaOnKill = new(43, "ManaOnKill");
    public static readonly AffixClass PoisonLengthReduced = new(44, "PoisonLengthReduced");
    public static readonly AffixClass PreventMonsterHeal = new(45, "PreventMonsterHeal");
    public static readonly AffixClass QuantityReplish = new(46, "QuantityReplish");
    public static readonly AffixClass QuantityIncreased = new(47, "QuantityIncreased");
    public static readonly AffixClass RequirementReduction = new(48, "RequirementReduction");
    public static readonly AffixClass ResistAll = new(49, "ResistAll");
    public static readonly AffixClass ResistCold = new(50, "ResistCold");
    public static readonly AffixClass ResistFire = new(51, "ResistFire");
    public static readonly AffixClass ResistLightning = new(52, "ResistLightning");
    public static readonly AffixClass ResistPoison = new(53, "ResistPoison");
    public static readonly AffixClass RunWalkSpeed = new(54, "RunWalkSpeed");
    public static readonly AffixClass RunWalkSpeedAndStaminaDrain = new(55, "RunWalkSpeedAndStaminaDrain");
    public static readonly AffixClass SelfRepair = new(56, "SelfRepair");
    public static readonly AffixClass Skills = new(57, "Skills");
    public static readonly AffixClass SpellCharge = new(58, "SpellChargeLevel");
    public static readonly AffixClass SpellProc = new(59, "SpellProcChance");
    public static readonly AffixClass Stamina = new(60, "Stamina");
    public static readonly AffixClass StaminaRegeneration = new(61, "StaminaRegeneration");
    public static readonly AffixClass Strength = new(62, "Strength");
    public static readonly AffixClass Vitality = new(63, "Vitality");
}
