using ItemGenerator.Domain.Common;

namespace ItemGenerator.Domain.Enumerations;

public sealed class ModifierType : Enumeration<ModifierType>
{
    private ModifierType(byte value, string name) : base(value, name) { }
    public static readonly ModifierType AddSockets = new(0, "AddSockets");
    public static readonly ModifierType AttackRating = new(1, "AttackRating");
    public static readonly ModifierType AttackRatingBasedOnCharacterLevel = new(2, "AttackRatingBasedOnCharacterLevel");
    public static readonly ModifierType AttackRatingPercentBasedOnCharacterLevel = new(3, "AttackRatingPercentBasedOnCharacterLevel");
    public static readonly ModifierType AttackRatingVsDemons = new(4, "AttackRatingVsDemons");
    public static readonly ModifierType AttackRatingVsUndead = new(5, "AttackRatingVsUndead");
    public static readonly ModifierType AttackSpeed = new(6, "AttackSpeed");
    public static readonly ModifierType CauseMonsterFlee = new(7, "CauseMonsterFlee");
    public static readonly ModifierType BlockRate = new(8, "BlockRate");
    public static readonly ModifierType BlockChance = new(9, "BlockChance");
    public static readonly ModifierType CastRate = new(10, "CastRate");
    public static readonly ModifierType DamageEnhanced = new(11, "DamageEnhanced");
    public static readonly ModifierType DamageEnhancedVsDemons = new(12, "DamageEnhancedVsDemons");
    public static readonly ModifierType DamageEnhancedVsUndead = new(13, "DamageEnhancedVsUndead");
    public static readonly ModifierType DamageColdMin = new(14, "DamageColdMin");
    public static readonly ModifierType DamageColdMax = new(15, "DamageColdMax");
    public static readonly ModifierType DamageFireMin = new(16, "DamageFireMin");
    public static readonly ModifierType DamageFireMax = new(17, "DamageFireMax");
    public static readonly ModifierType DamageLightningMin = new(18, "DamageLightningMin");
    public static readonly ModifierType DamageLightningMax = new(19, "DamageLightningMax");
    public static readonly ModifierType DamageMagicReduced = new(20, "DamageMagicReduced");
    public static readonly ModifierType DamagePoison = new(21, "DamagePoison");
    public static readonly ModifierType DamagePoisonDuration = new(22, "DamagePoisonDuration");
    public static readonly ModifierType DamagePhysicalMin = new(23, "DamagePhysicalMin");
    public static readonly ModifierType DamagePhysicalMax = new(24, "DamagePhysicalMax");
    public static readonly ModifierType DamageReduced = new(25, "DamageReduced");
    public static readonly ModifierType DamageReflect = new(26, "DamageReflect");
    public static readonly ModifierType DamagePhysicalMaxBasedOnCharacterLevel = new(27, "DamagePhysicalMaxBasedOnCharacterLevel");
    public static readonly ModifierType DamageTakenGoesToMana = new(28, "DamageTakenGoesToMana");
    public static readonly ModifierType Defense = new(29, "Defense");
    public static readonly ModifierType DefenseBasedOnCharacterLevel = new(30, "DefenseBasedOnCharacterLevel");
    public static readonly ModifierType DefenseEnhanced = new(31, "DefenseEnhanced");
    public static readonly ModifierType Dexterity = new(32, "Dexterity");
    public static readonly ModifierType Energy = new(33, "Energy");
    public static readonly ModifierType FreezeDuration = new(34, "FreezeDuration");
    public static readonly ModifierType GoldFind = new(35, "GoldFind");
    public static readonly ModifierType HitRecovery = new(36, "HitRecovery");
    public static readonly ModifierType IgnoreTargetDefense = new(37, "IgnoreTargetDefense");
    public static readonly ModifierType IncreasedStackSize = new(38, "IncreasedStackSize");
    public static readonly ModifierType Indestructable = new(39, "Indestructable");
    public static readonly ModifierType Knockback = new(40, "Knockback");
    public static readonly ModifierType Life = new(41, "Life");
    public static readonly ModifierType LifeBasedOnCharacterLevel = new(42, "LifeBasedOnCharacterLevel");
    public static readonly ModifierType LifeLeech = new(43, "LifeLeech");
    public static readonly ModifierType LifeRegeneration = new(44, "LifeRegeneration");
    public static readonly ModifierType LightRadius = new(45, "LightRadius");
    public static readonly ModifierType MagicFind = new(46, "MagicFind");
    public static readonly ModifierType Mana = new(47, "Mana");
    public static readonly ModifierType ManaBasedOnCharacterLevel = new(48, "ManaBasedOnCharacterLevel");
    public static readonly ModifierType ManaLeech = new(49, "ManaLeech");
    public static readonly ModifierType ManaOnKill = new(50, "ManaOnKill");
    public static readonly ModifierType PoisonLengthReduced = new(51, "PoisonLengthReduced");
    public static readonly ModifierType PreventMonsterHeal = new(52, "PreventMonsterHeal");
    public static readonly ModifierType QuantityReplish = new(53, "QuantityReplish");
    public static readonly ModifierType QuantityIncreased = new(54, "QuantityIncreased");
    public static readonly ModifierType RequirementReduction = new(55, "RequirementReduction");
    public static readonly ModifierType ResistAll = new(56, "ResistAll");
    public static readonly ModifierType ResistCold = new(57, "ResistCold");
    public static readonly ModifierType ResistFire = new(58, "ResistFire");
    public static readonly ModifierType ResistLightning = new(59, "ResistLightning");
    public static readonly ModifierType ResistPoison = new(60, "ResistPoison");
    public static readonly ModifierType RunWalkSpeed = new(61, "RunWalkSpeed");
    public static readonly ModifierType SelfRepair = new(62, "SelfRepair");
    public static readonly ModifierType Skills = new(63, "Skills");
    public static readonly ModifierType SpellChargeLevel = new(64, "SpellChargeLevel");
    public static readonly ModifierType SpellChargeQuantity = new(65, "SpellChargeQuantity");
    public static readonly ModifierType SpellChargeType = new(67, "SpellChargeType");
    public static readonly ModifierType SpellProcChance = new(68, "SpellProcChance");
    public static readonly ModifierType SpellProcType = new(69, "SpellProcType");
    public static readonly ModifierType SpellProcLevel = new(70, "SpellProcLevel");
    public static readonly ModifierType Stamina = new(71, "Stamina");
    public static readonly ModifierType StaminaRegeneration = new(72, "StaminaRegeneration");
    public static readonly ModifierType StaminaDrain = new(73, "StaminaRegeneration");
    public static readonly ModifierType Strength = new(74, "Strength");
    public static readonly ModifierType Vitality = new(75, "Vitality");
}